# Generated by Django 4.0.4 on 2022-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_latitude', models.CharField(max_length=100)),
                ('message_longitude', models.CharField(max_length=100)),
                ('message_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDetail',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.CharField(max_length=100)),
                ('sticker_keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
