# Generated by Django 4.0.4 on 2022-05-25 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuate_linebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
