# Generated by Django 4.0.4 on 2022-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuate_linebot', '0002_location_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetail',
            name='sticker_id',
            field=models.CharField(max_length=100, default=' '),
        ),
        migrations.AddField(
            model_name='messagedetail',
            name='sticker_package_id',
            field=models.CharField(max_length=100, default=' '),
        ),
        migrations.RemoveField(
            model_name='messagedetail',
            name='sticker_keyword',
        ),
    ]
